#!/bin/bash

echo "🌹 Blooming Rose Repository Setup"
echo "=================================="
echo ""
echo "To create and push to GitHub:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Create a new repository named 'blooming-rose' (or your preferred name)"
echo "3. Make it public or private as you prefer"
echo "4. DO NOT initialize with README (we already have one)"
echo "5. Copy the repository URL"
echo ""
echo "Then run these commands (replace YOUR_USERNAME with your GitHub username):"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/blooming-rose.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Or if you prefer SSH:"
echo "git remote add origin git@github.com:YOUR_USERNAME/blooming-rose.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Your repository is ready to push! 🚀" 